website/carpediem/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

from trading import views as tradingviews
from market import views as marketviews

urlpatterns = [
    # Admin pages
    url(r'^admin', admin.site.urls, name="admin"),
    #url(r'^$', RedirectView.as_view(pattern_name='overview', permanent=False)),

    # Record pages
    url(r'^$', tradingviews.Home.as_view(), name="home"),
    url(r'^trading/record', tradingviews.TradingView.as_view(), name="record"),
    url(r'^trading/account', tradingviews.AccountView.as_view(), name="account"),

    # Marketapp pages
    url(r'^market/', marketviews.MarketView.as_view(), name="market"),

    #Login/Logout URLs
    url(r'^login/$', 
     auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$',
     auth_views.logout, {'next_page': '/login/'}, name='logout'),

    #handle 404 : redirect to home
    url(r'.*?', tradingviews.Home.as_view(), name="home")
]

website/trading/models.py
from django.db import models
from django.forms import ModelForm
from django import forms
from django.db.models import Sum
from datetime import date, timedelta

# Create your models here.
class Product(models.Model):
    """ 상품 정보 """
    name = models.CharField(max_length=50, unique=True) # 상품명
    group = models.CharField(primary_key=True, max_length=30, unique=True) #그룹 코드
    market = models.CharField(max_length=10) #시장구분
    active = models.CharField(max_length=10,null=True, blank=True) #액티브 월물명
    front = models.CharField(max_length=10,null=True, blank=True) #근월물명
    activated_date = models.DateField(null=True, blank=True) #액티브 월물 변경일
    price_gap = models.DecimalField(max_digits=20, decimal_places=7, null=True, blank=True) #가격 갭 
    currency = models.CharField(max_length=10) #기준 통화
    open_margin = models.DecimalField(max_digits=10, decimal_places=2)
    keep_margin = models.DecimalField(max_digits=10, decimal_places=2)
    open_time = models.TimeField()
    close_time = models.TimeField()
    tick_unit = models.DecimalField(max_digits=20, decimal_places=7)
    tick_value = models.DecimalField(max_digits=20, decimal_places=3)
    commission = models.DecimalField(max_digits=5, decimal_places=2)
    notation = models.PositiveSmallIntegerField() # 진법
    decimal_places = models.PositiveSmallIntegerField()
    last_update = models.DateTimeField()
    is_favorite = models.BooleanField(blank=True, default=False)


    def __str__(self):
        return self.name

class Code(models.Model):
    """ 월물별 상품 정보 """
    code = models.CharField(primary_key=True, max_length=10)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    month = models.DateField() #만기월물
    ec_price = models.DecimalField(max_digits=20, decimal_places=7) #정산가격

    def __str__(self):
        return self.code


class Game(models.Model):
    # choices
    POSITION = (
        (1, 'Long'),
        (-1, 'Short')
    )

    #계획
    pub_date = models.DateField(default=date.today)
    product = models.ForeignKey('Product', on_delete=models.PROTECT, null=True, blank=True)
    name = models.CharField(max_length=50, blank=True)
    position = models.IntegerField(choices=POSITION) #포지션

    #결과
    profit = models.DecimalField(null=True, blank=True, max_digits=20, decimal_places=3) #손익
    profit_per_contract = models.DecimalField(null=True, blank=True, max_digits=20, decimal_places=3) #단위손익
    profit_to_risk = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=2)
    commission = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True) #수수료

    #완료
    is_completed = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if self.product:
            self.name = self.product.name

        agg = self.exit_set.all().aggregate(
            profit=Sum('profit'),
            commission=Sum('commission'),
            ppc=Sum('profit_per_contract'),
            ptr=Sum('ptr_ratio')
        )
        self.profit = agg.get('profit') if agg.get('profit') else 0
        self.profit_per_contract = agg.get('ppc')/self.exit_set.all().count() if agg.get('ppc') else 0
        self.profit_to_risk = agg.get('ptr')/self.exit_set.all().count() if agg.get('ptr') else 0
        self.commission = agg.get('commission') if agg.get('commission') else 0
        super(Game, self).save(*args, **kwargs)

    def __str__(self):
        return self.name + " #" + str(self.id)

class Entry(models.Model):
    """ 진입 내역 """
    game = models.ForeignKey('Game', on_delete=models.CASCADE)
    code = models.ForeignKey('Code', on_delete=models.PROTECT, null=True, blank=True)
    entry_date = models.DateTimeField() #진입날짜
    contracts = models.PositiveSmallIntegerField(default=1) #계약수
    entry_price = models.DecimalField(max_digits=20, decimal_places=7) #진입가격
    loss_cut = models.DecimalField(max_digits=20, decimal_places=7) #로스컷
    plan = models.CharField(max_length=50, null=True, blank=True) #매매전략
    done = models.BooleanField(default=False)

    def __str__(self):
        return self.game.name+' #'+str(self.id)


class Exit(models.Model):
    """ 청산 내역 """
    game = models.ForeignKey('Game', on_delete=models.CASCADE, null=True, blank=True)
    entry = models.ForeignKey('Entry', on_delete=models.CASCADE, null=True, blank=True)
    exit_date = models.DateTimeField() #청산날짜
    contracts = models.PositiveSmallIntegerField(default=1) #계약수
    exit_price = models.DecimalField(max_digits=20, decimal_places=7) #청산가격

    #단위 결과
    profit = models.DecimalField(blank=True, max_digits=20, decimal_places=3) #손익
    profit_per_contract = models.DecimalField(null=True, blank=True, max_digits=20, decimal_places=3) #단위손익
    commission = models.DecimalField(max_digits=5, decimal_places=2, blank=True) #수수료
    holding_period = models.DurationField(blank=True) #보유기간
    ptr_ratio = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=2) #ptr ratio

    def save(self, *args, **kwargs):
        # 손익 계산
        if self.game and self.game.product:
            product = self.game.product
            price_diff = (self.exit_price - self.entry.entry_price) * self.game.position
            tick_diff = round(price_diff/product.tick_unit)
            risk = round(abs(self.entry.loss_cut - self.entry.entry_price)/product.tick_unit)*product.tick_value
            self.commission = product.commission * self.contracts
            self.profit_per_contract = tick_diff * product.tick_value - product.commission
            self.profit = tick_diff * self.contracts * product.tick_value - self.commission
            self.holding_period = self.exit_date - self.entry.entry_date
            self.ptr_ratio = self.profit_per_contract / risk if risk else 0
        
        if self.entry:
            exit_cons = self.entry.exit_set.aggregate(Sum('contracts'))['contracts__sum']
            exit_cons = exit_cons + self.contracts if exit_cons else self.contracts
            entry_cons = self.entry.contracts

            if entry_cons == exit_cons:
                self.entry.done = True
            elif entry_cons > exit_cons:
                self.entry.done = False
            else:
                raise ValueError("exit contracts can not be grather than entry contracts")
            self.entry.save()
        
        super(Exit, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.exit_date)

class Equity(models.Model):
    date = models.DateField()
    principal = models.DecimalField(max_digits=10, decimal_places=2) #투자원금
    profit = models.DecimalField(default=0, max_digits=10, decimal_places=2) #확정손익
    estimated_profit = models.DecimalField(default=0, max_digits=10, decimal_places=2) #평가손익
    #total = models.DecimalField(max_digits=10, decimal_places=2) #총자산
    
    # equity db 업데이트
    def update_equity(self):
        self.principal = Account.objects.filter(date__lte=self.date).aggregate(Sum('usd'))['usd__sum']
        self.profit = Exit.objects.filter(exit_date__lte=self.date).aggregate(Sum('profit'))['profit__sum']
        self.estimated_profit = 0
        for entry in  Entry.objects.filter(done=False):
            product = entry.game.product
            exit_cons = entry.exit_set.aggregate(Sum('contracts'))['contracts__sum']
            contracts = entry.contracts - exit_cons if exit_cons else entry.contracts
            price_diff = (entry.code.ec_price - entry.entry_price) * entry.game.position
            tick_diff = round(price_diff/product.tick_unit)
            estim_profit = tick_diff * product.tick_value * contracts
            self.estimated_profit += estim_profit
        self.save()
    
    def __str__(self):
        return self.date.strftime("%Y-%m-%d")


class Account(models.Model):
    """
    계좌
    """
    date = models.DateField(null=True, blank=True)
    krw = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    usd = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    cash = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return str(self.date)


# Web forms
class GameForm(ModelForm):
    pub_date = forms.DateField(input_formats=['%Y-%m-%d'])
    class Meta:
        model = Game
        fields = [
            'pub_date',
            'name',
            'position',
        ]

class EntryForm(ModelForm):
    entry_date = forms.DateTimeField(input_formats=['%Y-%m-%d'])
    class Meta:
        model = Entry
        fields = [
            'entry_date',
            'entry_price',
            'contracts',
            'loss_cut',
            'plan',
        ]

class ExitForm(ModelForm):
    exit_date = forms.DateTimeField(input_formats=['%Y-%m-%d'])
    class Meta:
        model = Exit
        fields = [
            'exit_date',
            'exit_price',
            'contracts',
        ]


## Helper method #3
def recreate_equity():
    """ equity 테이블 초기생성시키는 함수"""
    dates = []
    for item in Exit.objects.all():
        dates.append(item.exit_date.date())
    dates = list(set(dates))
    dates.sort()
    for ndate in dates:
        equity = Equity()
        equity.date = ndate
        #equity, _ = Equity.objects.get_or_create(date=ndate)
        principal = Account.objects.filter(date__lte=ndate).aggregate(Sum('usd'))['usd__sum']
        equity.principal = principal if principal else 0
        profit = Exit.objects.filter(exit_date__lte=ndate).aggregate(Sum('profit'))['profit__sum']
        equity.profit = profit if profit else 0
        equity.save()

website/trading/forms.py
from django import forms

class EntryForm(forms.Form):
    entry_date = forms.DateTimeField(input_formats=['%Y-%m-%dT%H:%M:%S'])
    product_name = forms.CharField(max_length=50)
    position = forms.IntegerField() #포지션
    contracts = forms.IntegerField(min_value=1) #계약수
    entry_price = forms.DecimalField(max_digits=20, decimal_places=7) #진입가격
    loss_cut_in_ticks = forms.IntegerField()
    strategy = forms.IntegerField()

website/templates/trading/account.html
{% extends 'trading/base_trading.html' %}
{% load static %}
{% load humanize %}
{% block title %}Account{% endblock title %}

{% block trading_content %}
<div class="main">
    <div class="container-fluid">
        <!-- ========= 여기부터 매매결과 테이블 =========== -->
        <div class="balance-sheet" style="width:80%;margin: 0 auto;">
          <h4> 계좌 입출금 </h4>
          <table class="table table-condensed table-bordered table-hover table-striped statement-table">
              <thead>
                  <tr>
                      <th style='width:25%'>Date</th>
                      <th style='width:25%'>Cash</th>
                      <th style='width:25%'>KRW</th>
                      <th style='width:25%'>USD</th>
                  </tr>
              </thead>
              <tbody>
                {% for balance in account %}
                  <tr>
                      <td style='width:25%'>{{ balance.date |date:"Y-m-d" }}</td>
                      <td style='width:25%;
                        color: {% if balance.cash > 0 %}blue{% else %} red {% endif %}'>
                        {{ balance.cash | default:""| intcomma}}{{ balance.cash | yesno:" ₩, , "}}</td>
                      <td style='width:25%;
                        color: {% if balance.krw > 0 %}blue{% else %} red {% endif %}'>
                        {{ balance.krw | default:""| intcomma }}{{ balance.krw | yesno:" ₩, , "}}</td>
                      <td style='width:25%;
                        color: {% if balance.usd > 0 %}blue{% else %} red {% endif %}'>
                        {{ balance.usd | default:""| intcomma }}{{ balance.usd | yesno:" $, , "}}</td>
                      </td>
                  </tr>
                {% endfor %}
                  <tr>
                    <td style='width:25%;font-weight:bold'> Total </td>
                    <td style='width:25%;
                        color: {% if total.cash > 0 %}blue{% else %} red {% endif %}'>
                        {{ total.cash | default:""| intcomma}}{{ total.cash | yesno:" ₩, , "}}</td>
                    <td style='width:25%;
                        color: {% if total.krw > 0 %}blue{% else %} red {% endif %}'>
                        {{ total.krw | default:""| intcomma }}{{ total.krw | yesno:" ₩, , "}}</td>
                    <td style='width:25%;
                        color: {% if total.usd > 0 %}blue{% else %} red {% endif %}'>
                        {{ total.usd | default:""| intcomma }}{{ total.usd | yesno:" $, , "}}</td>
                  </tr>
              </tbody>
          </table>
<!-- ===============  Pagination  ===========================================--> 
      {% if is_paginated %}
        <ul class="pagination">
          {% if page_obj.has_previous %}
            <li class="page-item">
              <a href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
            </li>
          {% else %}
            <li class="disabled"><span>&laquo;</span></li>
          {% endif %}
          {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
              <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
            {% else %}
              <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
          {% endfor %}
          {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
          {% else %}
            <li class="disabled"><span>&raquo;</span></li>
          {% endif %}
        </ul>
        {% endif %}
        </div>
    </div>
</div>
{% endblock trading_content %}

website/templates/trading/base_trading.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Records{% endblock title %}

{% block content %}  

<nav class="navbar navbar-default sidebar" role="navigation" style="position:fixed">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
        </div>
        <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
            <ul class="nav navbar-nav navbutton" style="width:100%">
                <li {% if request.path == "/trading/record" %}class="active"{%endif%}><a href="{% url 'record' %}">매매기록<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-list-alt"></span></a></li>
                <li {% if request.path == "/trading/account" %}class="active"{%endif%}><a href="{% url 'account' %}">계좌관리<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-usd"></span></a></li>
            </ul>
        </div>
    </div>
</nav>
{% block trading_content %}{%endblock trading_content %}


{% endblock content %}

website/templates/trading/record.html
{% extends 'trading/base_trading.html' %}
{% load static %}
{% load humanize %}
{% block title %}Trading{% endblock title %}

{% block trading_content %}

<div class="main">
  <div class="container-fluid">
    <!-- ========= 여기부터 미결제 매매 =========== -->
    <div class="game">
      <h4> 진행중 </h4>
      <table class="table table-condensed table-bordered table-hover games">
          <thead>
            <tr>
              <th style='width:5%'>#</th>
              <th style='width:17%'>게시일</th>
              <th style='width:25%'>상 품</th>
              <th style='width:13%'>포지션</th>
              <th style='width:15%'>손 익</th>
              <th style='width:15%'>수익/위험</th>
              <th style='width:10%'>매매횟수</th>
            </tr>
            <tbody>
              {% for game in open_game %}
              <tr value={{game.id}}>
                <td style='width:5%'>{{ game.id }}</td>
                <td style='width:17%'>{{ game.pub_date |date:"Y-m-d" }}</td>
                <td style='width:25%'>{{ game.name }}</td>
                <td style="width:13%;
                  color: {% if game.position == 1 %}darkcyan {% else %} purple {% endif %}">
                    {% if game.position == 1 %}Long
                    {% elif game.position == -1 %}Short
                    {% endif %}
                  </td>
                <td style="width:15%;
                  color: {% if game.profit > 0 %}blue {% else %} red {% endif %}">
                  {{ game.profit | floatformat | intcomma }}</td>
                <td style="width:15%;
                  color: {% if game.profit_to_risk > 0 %}blue {% else %} red {% endif %}">
                  {{ game.profit_to_risk | floatformat}}</td>
                <td style='width:10%'>{{ game.entry_set.count }}</td>
              </tr>
              {% endfor %}
              <form id="game-form" action="{% url 'record' %}" method="post">
                {% csrf_token %}
                <input type="text" value="new_game" name="form_type" hidden></input>
                <tr id='new-game' hidden>
                  <td style='width:5%'></td>
                  <td style='width:17%'><input type='datetime' class='form-control input-sm' name='pub_date' required></td>
                  <td style='width:25%'><input type='text' class='form-control input-sm' name='name' required></td>
                  <td style='width:13%'><select class='form-control input-sm' name='position' required>
                   <option value=1>Long</option>
                   <option value=-1>Short</option>
                  </select></td>
                <td style='width:15%'></td>
                <td style='width:15%'></td>
                <td style='width:10%'></td>
                </tr>
            </tbody>
      </table>
      <p style="color: red; font-weight:bold; text-align:center;">
      {% if messages %}
          {% for message in messages %}
          {{ message }}
          {% endfor %}
      {% endif %}
      </p>
      <button id="save-button" type="submit" form="game-form" class="btn btn-default" style="font-weight: bold; width: 70px; float: right; display:none;">Save</button>
      <button id="add-button" type="button" onclick="newGame()" class="btn btn-default" style="font-weight: bold; width: 70px; float: right;">Create</button>
    </form>
    </div>
    <hr>
    <!-- ========= 여기부터 매매결과 테이블 =========== -->
    <div class="trading-records">
      <h4> 기록 </h4>
      <table class="table table-condensed table-bordered table-hover table-striped statement-table games">
          <thead>
              <tr>
                  <th style='width:5%'>#</th>
                  <th style='width:17%'>게시일</th>
                  <th style='width:25%'>상 품</th>
                  <th style='width:13%'>포지션</th>
                  <th style='width:15%'>손 익</th>
                  <th style='width:15%'>수익/위험</th>
                  <th style='width:10%'>매매횟수</th>
              </tr>
          </thead>
          <tbody>
            {% for game in games %}
              <tr value={{game.id}}>
                <td style='width:5%'>{{ game.id }}</td>
                <td style='width:17%'>{{ game.pub_date |date:"Y-m-d" }}</td>
                <td style='width:25%'>{{ game.name }}</td>
                <td style="width:13%;
                  color: {% if game.position == 1 %}darkcyan {% else %} purple {% endif %}">
                    {% if game.position == 1 %}Long
                    {% elif game.position == -1 %}Short
                    {% endif %}
                  </td>
                <td style="width:15%;
                  color: {% if game.profit > 0 %}blue {% else %} red {% endif %}">
                  {{ game.profit | floatformat | intcomma}}</td>
                <td style="width:15%;
                  color: {% if game.profit_to_risk > 0 %}blue {% else %} red {% endif %}">
                  {{ game.profit_to_risk | floatformat }}</td>
                <td style='width:10%'>{{ game.entry_set.count }}</td>
              </tr>
            {% endfor %}
          </tbody>
      </table>
    </div>

  <!-- ===============  Pagination  ===========================================--> 
  {% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
      </li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
  {% endif %}
  </div>
</div>


<!-- ===============  Modal for Game  ===========================================-->
<div class="container">
  <div class="modal" id="game-detail" role="dialog">
    <div class="modal-dialog modal-lg">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" onclick="closeModal()" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title" id='modal-title'></h4>
        </div>
        <div class="modal-body">
          <div class='entries'>
            <h4> 진 입
                  <td style='width:5%'>
                    <button type="button" class="btn btn-default btn-sm"
                            onclick="$('#new-entry-row').attr('hidden', !$('#new-entry-row').attr('hidden'))">
                     <span class="glyphicon glyphicon-plus" ></span></button>
                  </td>
            </h4>
            <table class="table table-condensed table-bordered table-hover" id="entry-table">
              <thead>
                <tr>
                  <th style='width:5%'>#</th>
                  <th style='width:20%'>날  짜</th>
                  <th style='width:16%'>가  격</th>
                  <th style='width:7%'>계약수</th>
                  <th style='width:16%'>손절가</th>
                  <th style='width:16%'>매매타입</th>
                  <th style='width:15%'>종목코드</th>
                  <th style='width:5%'></th>
                </tr>
              </thead>
              <tbody>
                <tr id='new-entry-row' hidden>
                  <td style='width:5%'></td>
                  <td style='width:20%'><input type='datetime' class='form-control input-sm' name='entry_date' required onclick="$(this).val(setNow('today'))"></td>
                  <td style='width:16%'><input type='number' class='form-control input-sm' name='entry_price' step='any' required></td>
                  <td style='width:7%'><input type='number' class='form-control input-sm' name='contracts' min='1' required></td>
                  <td style='width:16%'><input type='number' class='form-control input-sm' name='loss_cut' step='any' required></td>
                  <td style='width:16%'><select class='form-control input-sm' name='plan'>
                      <option value='Trend Following'>Trend Following</option>
                      <option value='Even Money' selected>Even Money</option>
                  </select></td>
                  <td style='width:15%'><select class='form-control input-sm' name='code' id="code">
                  </select></td>
                  <td style='width:5%'>
                    <button type="button" onclick='saveEntry()' class="btn btn-default btn-sm" id="new-entry-btn">
                     <span class="glyphicon glyphicon-ok" aria-hidden="true"></span></button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

          <hr>

          <div class='exits'>
            <h4> 청 산 </h4>
            <table class="table table-condensed table-bordered table-hover" id="exit-table">
              <thead>
                <tr>
                  <th style='width:5%'>#</th>
                  <th style='width:20%'>가  격</th>
                  <th style='width:10%'>계약수</th>
                  <th style='width:12%'>보유기간</th>
                  <th style='width:20%'>수  익</th>
                  <th style='width:20%'>단위수익</th>
                  <th style='width:7%'>P/R</th>
                  <th style='width:5%'></th>
                </tr>
                <tbody>
                  
                </tbody>
            </table>
            
            <br>
            <div id="new-exit" style="text-align: right" hidden>
                <input type="text" class='form-control input-sm' name="exit_id" style="display:none !important" hidden>
                <input type="text" class='form-control input-sm' name='entry_id' 
                       placeholder="Entry id" style='width:10%;cursor:default' disabled>
                <input type="number" class='form-control input-sm' name='exit_price' 
                       step='any' placeholder="exit price" style='width:20%'>
                <input type='number' class='form-control input-sm' name='exit_contracts'
                       min='1' style='width:20%' placeholder="contracts">
                <input type='datetime' class='form-control input-sm' name='exit_date' 
                       onclick="$(this).val(setNow('today'));" placeholder="exit date" style="width:25%">
                <button type="button" onclick='saveExit()' class="btn btn-default btn-sm" id="new-entry-btn">
                 <span class="glyphicon glyphicon-ok" aria-hidden="true"></span></button>
                <button type="button" onclick="$(this)[0].parentElement.hidden = true;" class="btn btn-default btn-sm" id="new-entry-btn">
                 <span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
            </div>
          </div>

          <hr>

          <div class='summary'>
            <h4> Summary </h4>
            <table class="table table-condensed table-bordered table-hover" id="summary-table">
              <thead>
                <tr>
                  <th style='width:25%'>총 수익</th>
                  <th style='width:25%'>평균 수익</th>
                  <th style='width:25%'>수수료</th>
                  <th style='width:25%'>매매횟수</th>
                </tr>
                <tbody>
                </tbody>
            </table>
          </div>

        </div>
        <div class="modal-footer">
          <p style="font-size:1.1em;font-weight:bold;float:left"> Complete 
            <input type='checkbox' name="complete"></input>
          </p>
          <form id="delete-form" action="{% url 'record' %}" method="post" style="display:inline" onsubmit="return confirm('Are you sure to delete the game?')">
            {% csrf_token %}
            <input type="text" name="form_type" value="delete_game" hidden></input>
            <input id="delete-id" type="text" name="id" hidden></input>
            <button id="delete-btn" type="submit" class="btn btn-default" style="font-weight:bold">Delete</button>
          </form>
          <button type="button" onclick="closeModal();" class="btn btn-default" data-dismiss="modal" style="font-weight:bold">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock trading_content %}